### ISSUE TITLE
Syntax highlighting in lstlisting

### ISSUE THREAD

**Issue by moospit** [area/language-latex#101]
I'm having some issues using language-latex in combination with `lstlistings`.

When there are ticks in a `lstlisting` like

![gh](https://cloud.githubusercontent.com/assets/11705573/19920971/04bced0a-a0dc-11e6-9b18-6bef9d0048d8.png)

the syntax highlighting gets broken and all text after the last `"` is highlighted as text in ticks.

Using a `verbatim` doesn't show this behaviour. Would it be possible to handle `lstlistings` like a `verbatim` environment in regards to syntax-highlighting?

Possibly related #87 ?

**Comment by PierreMarchand20** [comment]
I am having some trouble too with lstlisting and language-latex. For example: 
![capture d ecran 2016-11-08 a 23 07 42](https://cloud.githubusercontent.com/assets/15056323/20119310/538aaed2-a608-11e6-9f3f-33f3e659b2cb.png)

The syntax highlighting gets broken after the last `$`. I agree with moospit, a behavior like `verbatim` would be really great.

**Comment by tstumm** [comment]
Same when using minted 👍

**Comment by patgithub** [comment]
I manage this case by using a $ sign behind the initial statement which then does not occur in my output:

`\begin{lstlisting}[caption=buildtools/builders-alice.cfg]$`

**Comment by Aerijo** [comment]
Found your problem: this package does not support the lstlistings package ~~at all~~ properly. 

To begin a lstlistings environment, it needs to satisfy this (atom grammar package version) regex
```(?:\\s*)(\\\\begin)(\\{)(lstlisting)(\\})(\\[)(?:.*\\blanguage\\s*=\\s*Python\\b.*)(\\])```
In normal regex it would be
```(?:\s*)\\begin\{lstlisting\}\[(?:.*\blanguage\s*=\s*Python\b.*\])```
Try the normal regex on https://regex101.com/r/u4HCqg/1

This means it will look for \begin{lstlisting} AND, immediately following this, a pair of square brackets containing the words language=Python at the end. The only other supported language is Java.

As you do not provide the square brackets, it is not detecting the lstlisting environment. Hence, it detects the combination of "> as some kind of French quotation mark (check the scope), starts highlighting everything inside the quote green, and continues until it finds an end quote (experimenting shows this is "<). As it never finds one, the rest of the file is green. Similar thing is happening with the $ signs: they are being picked up as mathmode entries/exits because the scope is still regular latex.

A fix would involve changing the regex to properly detect lstlisting and minted environments. But I  ~~don't feel like fixing this~~ can't edit this repo.

**Comment by yudai-nkt** [comment]
This should be fixed in v1.1.0. Feel free to reopen if you still see some problems.

**Comment by PierreMarchand20** [comment]
I have just installed the last version (1.1.0) and my example is still broken:
![capture d ecran 2017-08-16 a 17 19 38](https://user-images.githubusercontent.com/15056323/29370944-32869ada-82a7-11e7-97ce-8e8816d0b19b.png)

**Comment by yudai-nkt** [comment]
@PierreMarchand20 should be fixed in v1.1.1. sorry for inconvenience.
