### ISSUE TITLE
$$ and \[\] aren't highlighted

### ISSUE THREAD

**Issue by sn0wyfall** [area/language-latex#112]
I'm not sure whether it's just because of a setting I have wrongly set, but `$$` and `\[ \]` aren't highlighted at all when I'm using this package.

**Comment by Aerijo** [comment]
Do you still have this issue?
If you do, does it happen in an otherwise empty file (no environments, brackets, etc.)?
Finally, what is the result of pressing <kbd>cmd</kbd> + <kbd>alt</kbd> + <kbd>p</kbd> (Mac) with the cursor within the $$ section

If not using Mac go into developer console and, using the select tool, hover within the $$ section. The tooltip should display something like "span.syntax--<something>.syntax--<something_else>".

**Comment by sn0wyfall** [comment]
Well I don't use it anymore (I've switched over to Sublime Text), so sorry. I could close this issue.
