### ISSUE TITLE
URL Highlighting in BibTeX is incorrect

### ISSUE THREAD

**Issue by Benjamin-Lee** [area/language-latex#187]
### Prerequisites
- [x] Put an `X` in this box if you have done the following:
  - Ensured the issue has not already been raised
  - Ensured the issue is caused by this package
  - Run `atom --safe`, activated this package, and the issue persisted

### Steps to reproduce & Minimum working example
1.

```
@article{Gates1986,
  doi = {10.1016/s0022-5193(86)80144-8},
  url = {https://doi.org/10.1016/s0022-5193(86)80144-8},
  year  = {1986},
  month = {apr},
  publisher = {Elsevier {BV}},
  volume = {119},
  number = {3},
  pages = {319--328},
  author = {Michael A. Gates},
  title = {A simple way to look at {DNA}},
  journal = {Journal of Theoretical Biology}
}
```

#### Expected behaviour

The entire URL should be highlighted

#### Actual behaviour

Only part of the URL is highlighted

### Additional information

See the screenshot

![screen shot 2018-07-06 at 12 13 02 pm 1](https://user-images.githubusercontent.com/13618205/42396302-f9637f34-8115-11e8-8598-026bc17e2f4d.png)

**Comment by Aerijo** [comment]
@Benjamin-Lee Hi, this is completely unrelated, but are you using `gost` as your reference style? I'm writing a biblatex linter, and I'm trying to find which style allows `publisher` in an `article` entry. I haven't seen it declared in any of the datamodel files (except `gost`), so I'm wondering if it could be an alias defined elsewhere (but haven't found it yet).

As for the syntax issue, I believe that URL highlighting is provided by the [`language-hyperlink`](https://atom.io/packages/language-hyperlink) core package. I doubt they can fix it either, because it's quite general and needs to be careful about what it is highlighting.

**Comment by Benjamin-Lee** [comment]
Thanks for referring me to `language-hyperlink` – I'll submit this issue there.

As for the reference style, I'm autogenerating my references from their DOIs using [doi2bib.org](https://doi2bib.org) but can't figure out exactly how they're doing it in their [repo](https://github.com/davidagraf/doi2bib2). Sorry I can't help more!

**Comment by Aerijo** [comment]
Closing in favour of https://github.com/atom/language-hyperlink/issues/24
