### ISSUE TITLE
Comment Package

### ISSUE THREAD

**Issue by ptrsinclair** [area/language-latex#46]
It would be nice if multi-line comments created via the comment package were supported. For those not familiar, a multi-line comment would look like:
> Non-commented text
> \begin{comment}
> Commented text
> \end{comment}
> Non-commented text

**Comment by cedhuf** [comment]
Hi,
You have build in commenting option via `edit-toggle comment` menu. It add a % at the beginning of every selected line, those lines won't be compiled. Sometimes if you don't have this option, or for more flexibility, you can use the `\begin{comment}` with the right package. Since we can only choose one default way of commenting via atom menu we will stick with `%` witch is the most standard way.

Anyway it's stil pretty easy to comment using `\begin{comment}` with the use of the beg snippet (type `beg` then press tab).

Hope this will answer your question.
