### ISSUE TITLE
expl3 syntax highlighting

### ISSUE THREAD

**Issue by Evpok** [area/language-latex#48]
Same as https://github.com/textmate/latex.tmbundle/issues/79 it would be really useful if the blocks between `\ExplSyntaxOn` and `\ExplSyntaxOff` could be properly highlighted.

**Comment by yudai-nkt** [comment]
Hi @Evpok,

Since the original maintainers are somehow inactive on this package for almost one year, I am now making a new one ([yudai-nkt/language-tex](https://github.com/yudai-nkt/language-tex)) based on the clone of this repo. Several bugs are fixed and `expl3` highlight is also support to some extent in [`expl3`](https://github.com/yudai-nkt/language-tex/tree/expl3) branch.

It's been a while since you opened this issue, but I'm glad if you get interested in my package and give it a try.

This is how `expl3` syntax looks with my package (example taken from `siunix` package):

![2016-07-16 20 39 35](https://cloud.githubusercontent.com/assets/13291527/16894616/867fc808-4b96-11e6-808a-6b911c427959.png)

As you can see in the screenshot above, current implementation is not perfect. For example, commenst are not rendered as comment. This is not included in the picture, but control sequences like `\newcommand` and `\ifx` are in the same color as the other ordinary macros. This problem has to be settled to merge into `master`.

Another problem is that because I'm not an expert of `expl3` grammar, the current pattern matching is quite _rough_ (especially, function and variable are not distinguished). If someone can invent better regex to represent the syntax, it will be highly appreciated also.

**Comment by Evpok** [comment]
Hi @yudai-nkt ! Thanks for following up on this issue and taking the burden of this package. I'll be glad to test it as soon as I come back from vacations, but I have to admit that it not being available via apm is a bit of a show-stopper for those of us with synchronized settings on several machines. 

I'll be happy to try and help support LaTeX3/expl syntax, though I have to admit that the Textmate syntax feels really alien to me.

**Comment by yudai-nkt** [comment]
I will surely publish my package when it's ready, but it won't include `expl3` support because it's not in `master` branch. Since `expl3` branch obviously contains bugs, I am reluctant to merge it.

However, the maleffect is limited between `\ExplSyntaxOn` and `\ExplSyntaxOff` or in packages with `\ProvideExplPackage`, so I should consider to merge for the convenience of those who are kind to take their time for the test.

> the Textmate syntax feels really alien to me

It's alien to me too :sob: There are [incomprehensible piles of `\t`](https://github.com/yudai-nkt/language-tex/blob/master/grammars/latex.cson#L60) and entries which seem to be ported from TextMate and unnecessary.

**Comment by yudai-nkt** [comment]
Hi, this is me again.

With the release of `language-tex` [v0.3.0](https://github.com/yudai-nkt/language-tex/releases/tag/v0.3.0), `expl3` syntax is fully supported! Unlike the previous one above, this version distinguishes variable, function and its argument specification. It also does not override the original setting such as `%` anymore.

![2016-08-27 1 40 44](https://cloud.githubusercontent.com/assets/13291527/18013071/74247e48-6bf7-11e6-930a-199f72216716.png)

FYI only.
