### ISSUE TITLE
Text is highlighted as equation

### ISSUE THREAD

**Issue by askielboe** [area/language-latex#59]
Loading up an old manuscript in Atom presented me with some highlighted text that shouldn't be highlighted.

I've tried to cut it down as much as possible, but I'm afraid this was the shortest I could get it.

`\a` is any math symbol
`0` is any number
`a` is any letter

Note that some of the whitespace before closing `$` are required.

    $\a \a \a 0 \a^\a{a} \a^\a{a} \a^\a{a} \a^\a{a} $ $\a \a \a \a \a 0 \a $ $\a\a $ $^{a} \a 0$ $^{a}$ this text should not be colored

This is what it looks like in Atom on Mac:

![](http://i.imgur.com/pqsN4mC.png)

**Comment by diracdeltafunk** [comment]
This problem is VERY prevalent in my files. I don't know what's causing it, but it's basically made atom unusable as a LaTeX editor for the time being (for me, at least). Bump.

**Comment by bkushigian** [comment]
I've also had the same problem, with the addition that some things that should be highlighted are not. This is on Ubuntu.

**Comment by bkushigian** [comment]
This isn't a latex-language bug. This is an atom bug. Long strings break other grammars as well.

**Comment by aj-foster** [comment]
Just for reference, this is the related issue for Atom: https://github.com/atom/atom/issues/1667

In the comments, one user created a [package](https://atom.io/packages/grammar-token-limit) that can be used to work around the issue. Note there are performance implications for this.

**Comment by area** [comment]
The provided example seems to be fixed, at least. 

<img width="874" alt="screen shot 2016-10-02 at 08 32 29" src="https://cloud.githubusercontent.com/assets/311812/19019302/f4223f14-887a-11e6-9724-6203551e13b3.png">

So between that and the fact that this was due to an inherent limit in Atom, I'm going to close this issue. If there's another example, and it can be shown that it's not due to the token limit in Atom though, I'll take another look.
