### ISSUE TITLE
Error when opening latex files... Cannot spawn texbin?

### ISSUE THREAD

**Issue by guziy** [area/language-latex#66]
Hi I am getting error messages from the plugin every time I open Latex files or try to save it...
I've checked that the problem comes from this plugin, since it goes away when the plugin is disabled.

Failed to spawn command /usr/texbin/. Make sure /usr/texbin/ is installed and on your PATH
Close All
Error: spawn /usr/texbin/ ENOENT
Error: spawn /usr/texbin/ ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)

Please see the screenshot below:

![screen shot 2016-01-04 at 5 58 20 pm](https://cloud.githubusercontent.com/assets/900941/12102999/ecb65c36-b30c-11e5-8305-01fa054019af.png)

Thanks

**Comment by area** [comment]
I honestly can't figure out why this plugin would be trying to touch this path. Are you sure there isn't another LaTeX plugin you're using that's trying to compile your file when you open it, somehow?

I'm guessing this is related to the changes introduced in OSX El Capitan (see [here](https://tug.org/mactex/elcapitan.html). I'm pretty sure that even if this was due to this plugin, the underlying problem was a bad install/upgrade of MacTex, and that no changes are required to this plugin.

If you're still seeing this, especially after fixing/reinstalling MacTex, or if I'm off on my assumption you're using ~~OSX~~ MacOS, I'd be very interested in more details.
